### ISSUE TITLE
Unable to connect to the main server

### ISSUE THREAD

**Issue by Vladg24YT** [LilyBukkit/Nebula#2]
```
java.lang.IndexOutOfBoundsException: Range [1, 1 + -1) out of bounds for length 262144
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:361)
	at java.base/java.util.Objects.checkFromIndexSize(Objects.java:411)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:129)
	at net.md_5.bungee.packet.PacketStream$TrackingInputStream.read(PacketStream.java:97)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at net.md_5.mendax.datainput.Instruction.skip(Instruction.java:34)
	at net.md_5.mendax.datainput.Jump.read(Jump.java:23)
	at net.md_5.mendax.datainput.ShortHeader.read(ShortHeader.java:22)
	at net.md_5.mendax.datainput.DataInputPacketReader.readPacket(DataInputPacketReader.java:84)
	at net.md_5.mendax.datainput.DataInputPacketReader.readPacket(DataInputPacketReader.java:91)
	at net.md_5.bungee.packet.PacketStream.readPacket(PacketStream.java:61)
	at net.md_5.bungee.InitialHandler.run(InitialHandler.java:172)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Vladg24YT** [comment]
Error occures when Nebula tries to read a ShortHeader of `Packet2Handshake`

**Comment by Vladg24YT** [comment]
It wasn't an error
